name: Checkout repository and apply patches

inputs:
  ref:
    type: string

  repository:
    type: string

runs:
  using: "composite"

  steps:
    - name: Checkout ${{ inputs.repository }} (${{ inputs.ref }})
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}
        repository: ${{ inputs.repository }}
        path: ${{ github.workspace }}/${{ inputs.repository }}

    - name: Apply patches
      shell: bash
      run: |
        # Directory with patches
        PATCHES_PATH="${{ github.workspace }}/patches/${{ inputs.repository }}"

        # Go to target directory
        cd "${{ github.workspace }}/${{ inputs.repository }}"

        # If patches exists
        if [ -d "$PATCHES_PATH" ]; then
          # Apply patches
          for patch in "$PATCHES_PATH"/*; do
            # Apply patch
            if [[ "$patch" == *.patch ]]; then
              # Log patch name
              echo "Applying patch $patch..."

              # Apply
              patch --no-backup-if-mismatch --strip=1 < "$patch" || exit 1
            fi

            # Apply script
            if [[ "$patch" == *.sh ]]; then
              # Log script name
              echo "Applying script $patch..."

              # Apply
              bash "$patch" || exit 1
            fi
          done
        fi

    - name: Export repository prefix
      shell: bash
      run: |
        echo "PREFIX=${{ github.workspace }}/${{ inputs.repository }}" >> "$GITHUB_ENV"
