name: Build for Android

jobs:
  bootstrap:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: termux/termux-packages

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clone and patch
        uses: ./.github/actions/clone-and-patch
        with:
          ref: bootstrap-2024.11.10-r1+apt-android-7
          repository: termux/termux-packages

      - name: Build bootstrap
        working-directory: ${{ env.PREFIX }}
        run: >
          scripts/run-docker.sh
          scripts/build-bootstraps.sh
          --android10
          --architectures ${{ matrix.architecture }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bootstrap-${{ matrix.architecture }}
          path: ${{ env.PREFIX }}/bootstrap-${{ matrix.architecture }}.zip

    strategy:
      matrix:
        architecture:
          - aarch64
          - arm
          - i686
          - x86_64

  app:
    needs: bootstrap
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clone and patch
        uses: ./.github/actions/clone-and-patch
        with:
          ref: v0.118.1
          repository: termux/termux-app

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: ${{ env.PREFIX }}/app/src/main/cpp
          pattern: bootstrap-*

      - name: Build Termux
        working-directory: ${{ env.PREFIX }}
        run: ./gradlew assembleDebug

on:
  - push
  - workflow_dispatch
